version: '3'

services:

  peer-server:
    image: peerjs/peerjs-server:0.6.1
    ports:
      - 9000:9000
    expose:
      - "9000"
    command: ["peerjs", "--port", "9000", "--key", "peerjs", "--path", "/myapp"]
    networks:
      - node-network


  dut-server:
    build: ./
    volumes:
      - .:/usr/src/dut-server
    ports:
      - 3000:3000
    depends_on:
      - peer-server
    networks:
    - node-network

networks:
  node-network:
      driver: bridge
